### ISSUE TITLE
Publish release candidates somewhere else

### ISSUE THREAD

**Issue by bluefireoly** [Dominaezzz/matrix-kt#1]
Currently you are publishing the release candidates to GitHub, but it is not possible to consume them from there (at least I don't think so, let me know if this isn't the case)

It would be great if you could publish them to somewhere else, where they can actually be used in projects.

Thank you!

**Comment by Dominaezzz** [comment]
Oh hello! Thank you for your interest in the project!

I was publishing to BinTray but they're shutting down, so I'm migrating to GitHub packages for now.
Haven't bothered with `mavenCentral()` yet as it's a faff to setup and I didn't think anyone was using this library lol.

You can indeed consume this library from GitHub as long as you have a GitHub account.
You just need to create a github token in settings that can `read:packages` only.
Then change the repository to this.
```
maven("https://maven.pkg.github.com/Dominaezzz/matrix-kt") {
    credentials {
        username = System.getenv("GITHUB_USER") // bluefireoly
        password = System.getenv("GITHUB_TOKEN") // PAC
    }
}
```

I'll update the instructions when I update master.
Lemme know how it goes.

**Comment by bluefireoly** [comment]
Oh, thank you!
Actually this wasn't made very clear on GitHub's side.

Now I am able to add the dependency to my project, but it seems that things like `MatrixClient` do not exist anymore. Is this the case because it got removed in version `0.1.4` or am I overseeing something here?

I am using the following dependency:
```kotlin
implementation("io.github.matrixkt:client:0.1.4-RC8")
```
which successfully adds the `client-jvm` module to my Kotlin/JVM project.

**Comment by Dominaezzz** [comment]
Yeah I got rid of MatrixClient, as it had a couple issues.
Check out the readme in the `ktor_locations` branch.

**Comment by bluefireoly** [comment]
Alright, got it! Thank you for creating this project :)

**Comment by Dominaezzz** [comment]
Changes have been merged into `master`.
